[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/auth.html"
  status = 200
  force = true

[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200
  force = true

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/app.html"
  status = 200
